### ISSUE TITLE
ImportError: Start directory is not importable: 'tests/test_xxx.py'

### ISSUE THREAD

**Issue by joshwapohlmann** [lgsvl/PythonAPI#16]
**Version:** Using 414d7ef6 (also taged 2020.01)

## Steps to Reproduce
1. `$ python3 -m venv env && . /env/bin/activate`
2. `$ pip3 install -e .`
3. `$ python3 -m unittest -v -c tests/test_XXXX.py`

## Expected behavior
Test runs succesfully

## Actual behavior
ImportError
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.6/unittest/main.py", line 118, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.6/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.6/unittest/loader.py", line 338, in discover
    raise ImportError('Start directory is not importable: %r' % start_dir)
ImportError: Start directory is not importable: 'tests/test_EGO.py'
```

**Comment by lemketron** [comment]
@joshwapohlmann Did you ever figure out why this was happening? We're unable to reproduce it.

**Comment by joshwapohlmann** [comment]
No, not really, I did not solve this, just ignored tests.
If you cannot reproduce it, it might have been an issue with my paths I guess.
