### ISSUE TITLE
problem while installing PythonAPI

### ISSUE THREAD

**Issue by chandra1618** [lgsvl/PythonAPI#20]
Obtaining file:///home/chandrashekhar/Documents/PythonAPI/PythonAPI
Collecting websockets==7.0 (from lgsvl==0.0.0)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://packagecloud.io/github/git-lfs/pypi/simple/websockets/

**Comment by chandra1618** [comment]
It is somewhere related to pypi not found on packagecloud/github/git-lfs

**Comment by hadiTab** [comment]
How are you installing it?

**Comment by chandra1618** [comment]
After cloning the PythonAPI repo i run this command in terminal
pip3 install --user -e .

**Comment by hadiTab** [comment]
The PythonAPI's only dependency is `websockets` version 7.0 which seems to be what is failing here. Do you get the same message if you try to install it manually? i.e. `pip3 install --user websockets==7.0`.

**Comment by chandra1618** [comment]
chandrashekhar@chandrashekhar:~/Documents/PythonAPI/PythonAPI$ pip3 install --user -e .
Obtaining file:///home/chandrashekhar/Documents/PythonAPI/PythonAPI
Collecting websockets==7.0 (from lgsvl==0.0.0)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://packagecloud.io/github/git-lfs/pypi/simple/websockets/
chandrashekhar@chandrashekhar:~/Documents/PythonAPI/PythonAPI$

**Comment by chandra1618** [comment]
![Screenshot from 2020-04-08 13-36-20](https://user-images.githubusercontent.com/34679608/78759946-0726d300-799e-11ea-8371-ec79231a6755.png)

**Comment by hadiTab** [comment]
I'm not sure what the issue it. Maybe you should ask on the [websockets repo](https://github.com/aaugustin/websockets) since it seems like it's related to them. Although I have no issues installing websockets 7.0 locally.

**Comment by lemketron** [comment]
@chandra1618 Were you able to resolve this?
