### ISSUE TITLE
Python current_scene method hangs

### ISSUE THREAD

**Issue by ebadi** [lgsvl/PythonAPI#39]
I am trying to run [NHTSA/Encroaching-Oncoming-Vehicles](https://github.com/lgsvl/PythonAPI/blob/master/examples/NHTSA/Encroaching-Oncoming-Vehicles/EOV_S_25_20.py) PythonAPI examples but it blocks [on this line](https://github.com/lgsvl/PythonAPI/blob/master/examples/NHTSA/Encroaching-Oncoming-Vehicles/EOV_S_25_20.py#L37). I ran LGSVL in API Only mode and in the first try I get this error message:

```
./EOV_test_runner.sh 

Traceback (most recent call last):
  File "EOV_S_25_20.py", line 41, in <module>
    sim.load(scene_name)
  File "/home/wave/.local/lib/python3.6/site-packages/lgsvl/utils.py", line 23, in new_f
    return f(*args, **kwargs)
  File "/home/wave/.local/lib/python3.6/site-packages/lgsvl/simulator.py", line 43, in load
    self.remote.command("simulator/load_scene", {"scene": scene, "seed": seed})
  File "/home/wave/.local/lib/python3.6/site-packages/lgsvl/remote.py", line 69, in command
    raise Exception(data["error"])
Exception: Environment '671868be-44f9-44a1-913c-cb0f29d12634' is not available
```
In the second try, it hangs and when I press CTRL+c :
```
wave@wave:~/repositories/PythonAPI-LGSVL/examples/NHTSA/Encroaching-Oncoming-Vehicles$ ./EOV_test_runner.sh 
./EOV_test_runner.sh 
EOV_S_25_20 - Here
^CTraceback (most recent call last):
  File "EOV_S_25_20.py", line 38, in <module>
    if sim.current_scene == scene_name:
  File "/home/wave/.local/lib/python3.6/site-packages/lgsvl/simulator.py", line 57, in current_scene
    return self.remote.command("simulator/current_scene")
  File "/home/wave/.local/lib/python3.6/site-packages/lgsvl/remote.py", line 64, in command
    self.cv.wait_for(lambda: self.data is not None)
  File "/usr/lib/python3.6/threading.py", line 330, in wait_for
    self.wait(waittime)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt

```
Python API branch: 2020.06
LGSVL version: lgsvlsimulator-linux64-2020.06.zip

**Comment by ebadi** [comment]
I realized that several maps are missing in my LGSVL installation. (Here environment
**671868be-44f9-44a1-913c-cb0f29d12634** refers to **Straight2LaneOpposing** map available at https://wise.svlsimulator.com/maps/profile/671868be-44f9-44a1-913c-cb0f29d12634

I tried to install the map from web interfaces resulted in:
Invalid: Missing or wrong Map AssetBundle. Please check content website for updated bundle or rebuild the bundle.

How can I install this map?

**Comment by ebadi** [comment]
The issue is resolved, apparently I checkout a wrong tag.
