### ISSUE TITLE
add_agent NPC error

### ISSUE THREAD

**Issue by xiejingjacob** [lgsvl/PythonAPI#65]
When I run the quickstart/08-create-npc.py

I got errors 

Python API Quickstart #8: Creating various NPCs

Traceback (most recent call last):

  File "./quickstart/08-create-npc.py", line 40, in <module>

    npc = sim.add_agent("Sedan", lgsvl.AgentType.NPC)

  File "/home/xj/PythonAPI/lgsvl/utils.py", line 23, in new_f

    return f(*args, **kwargs)

  File "/home/xj/PythonAPI/lgsvl/simulator.py", line 164, in add_agent

    uid = self.remote.command("simulator/add_agent", args)

  File "/home/xj/PythonAPI/lgsvl/remote.py", line 69, in command

    raise Exception(data["error"])

Exception: Object reference not set to an instance of an object

running in ubuntu20.04

**Comment by tjx1233** [comment]
I have same problem here, when using simulator.exe built from source code(2021.3). The release version is fine.

**Comment by Daparrag** [comment]
any update regarding this issue?
